osx_image: xcode7.3
language: objective-c
branches:
  only:
    master
cache: cocoapods
before_install:
  - gem install activesupport -N
  - gem install slather --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods
  - pod --version
  - pod setup --silent > /dev/null
  - pod repo update --silent
script:
  - set -o pipefail
  - xcodebuild test -workspace Traffic.xcworkspace -configuration Release -scheme Traffic -sdk iphonesimulator9.3 | xcpretty
after_success:
  - slather

